services:
  - type: web
    name: wavelength-music-player
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "python server/main.py"
    envVars:
      - key: JWT_SECRET
        generateValue: true

